<a href="https://colab.research.google.com/github/jgprps/studious-giggle/blob/master/firstStatMethods.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import numpy as np
arr = 10 * np.random.randn(2,5) #generate an array of random numbers in a 2 row by 5 col matrix
print(arr)
print(arr.mean())
#compute mean by row
print(arr.mean(axis=1)) #get an array of means per row. Axis = 0 for column mean
print(arr.sum())
print(np.median(arr, axis = 1)) #median of rows
arr.sort()
print(arr)





[[ -5.91617764   7.68384088  -2.92679551  12.26978813  -4.70531877]
 [-15.20871365   4.50523483   2.19625733   1.39927343  -2.51465303]]
-0.3217263988110886
[ 1.28106742 -1.92452022]
-3.217263988110886
[-2.92679551  1.39927343]
[[ -5.91617764  -4.70531877  -2.92679551   7.68384088  12.26978813]
 [-15.20871365  -2.51465303   1.39927343   2.19625733   4.50523483]]
