<a href="https://colab.research.google.com/github/jgprps/studious-giggle/blob/master/first_slice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np 
arr = np.zeros((3,3)) 
print(arr) 
arr_slice = arr[:2,] 
print(arr_slice)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 0. 0.]]


Note in code above, the first argument of zeros is (shape) so you need parens around that argument as well as ALL arguments.  Hence the double parens.