<a href="https://colab.research.google.com/github/jgprps/studious-giggle/blob/master/firstFilter.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
an_array = np.array([[11,12], [21,22], [31,32]])
print(an_array)

[[11 12]
 [21 22]
 [31 32]]


In [3]:
filter = (an_array > 15)  
filter

array([[False, False],
       [ True,  True],
       [ True,  True]])

In [5]:
an_array[an_array > 15] # can apply filter directly

array([21, 22, 31, 32])

In [7]:
an_array[an_array % 2 == 0] +=100 #modify the array in situ adding 100 to all elements that meet the filter even number
print(an_array)

[[ 11 212]
 [ 21 222]
 [ 31 232]]
